# connect with mongosh "mongodb://root:rootpassword@localhost:27017"
services:
   mongodb:
      image: mongodb/mongodb-community-server:8.0-ubi8
      container_name: mongodb
      ports:
         - "27017:27017"
      environment:
         MONGO_INITDB_ROOT_USERNAME: root
         MONGO_INITDB_ROOT_PASSWORD: rootpassword
      volumes:
         - mongo-data:/data/db

volumes:
   mongo-data:
